name: CI Test Services

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create .env files
        run: |
          echo "MONGODB_AUTH_URI=mongodb://localhost:27017/AuthService" >> auth/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env

          echo "MONGODB_PRODUCT_URI=mongodb://localhost:27017/ProductService" >> product/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
          echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
          echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

          echo "MONGODB_ORDER_URI=mongodb://localhost:27017/OrderService" >> order/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> order/.env

      - name: Install dependencies for all services
        run: |
          cd auth && npm ci
          cd ../product && npm ci
          cd ../order && npm ci
          cd ../api-gateway && npm ci
          cd ..

      - name: Start Auth service
        working-directory: ./auth
        run: |
          nohup npm start &
          sleep 8

      - name: Run Product tests
        working-directory: ./product
        # run: npm test
        run: NODE_ENV=test npm test

      - name: Run Order tests
        working-directory: ./order
        run: npm test
